
version: '3'
services:
  db:
    image: againdb
    volumes:
      - ~/.mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  webserver:
    image: nodeimage
    ports:
      - "4000:4000"
    links:
        - db
